### ISSUE TITLE
There is an ability to exceed character limit

### ISSUE THREAD

**Issue by EugeneMsv** [w8tcha/CKEditor-WordCount-Plugin#197]
After we reach character limit, we keep going to tap keyboard simultaneously pressing enter+any character, we can add more characters to the editor.
I reproduce even on the  demo page: 
http://w8tcha.github.io/CKEditor-WordCount-Plugin/

![image](https://user-images.githubusercontent.com/11499112/71479687-8d137980-2806-11ea-9156-2af28cccc2df.png)

**Comment by w8tcha** [comment]
Sorry for the late reply. Issue should be fixed now

**Comment by EugeneMsv** [comment]
Sorry, but it  still exists on the demo page.
![image](https://user-images.githubusercontent.com/11499112/72683813-de541780-3aeb-11ea-94ba-257cd89a7dcb.png)

**Comment by w8tcha** [comment]
I cant reproduce this. did you clear the browser cache ?

**Comment by EugeneMsv** [comment]
@w8tcha yes I cleared.

Just type some characters simultaneously and tap enter. 
Try do it at least 20 times. You will see the result

**Comment by w8tcha** [comment]
Atleast with chrome i cant reproduce this.

**Comment by EugeneMsv** [comment]
I've tired to prove you.
But still plugin doesn't work.

**Comment by w8tcha** [comment]
Well this is the same problem as #198 the current delay of 250 ms is causing this. if you dont like it you can set the value to 0 but this would make the plugin unstable and is causing memory leaks. If thats what you want no problem.

**Comment by Kitwradr** [comment]
@w8tcha how to reduce the delay?

**Comment by w8tcha** [comment]
> @w8tcha how to reduce the delay?

It doesnt seem to really work with the reduces delay. but i committed a fix for that issue
